=== LeonardoHP29/tecweb/practicas/p14/spotify.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified"
    vc:minVersion="1.0" vc:maxVersion="1.1">

    <xs:element name="Spotify">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Cuenta" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Nombre" type="xs:string"/>
                            <xs:element name="Correo" type="xs:string"/>
                            <xs:element maxOccurs="1" minOccurs="0" name="Telefono">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="Tipo" type="xs:string"
                                                use="required"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
                        <xs:attribute name="plan" type="xs:string" use="required"/>
                        <xs:attribute name="fechaIni" type="xs:date" use="optional"/>
                        <xs:attribute name="fechaFin" type="xs:date" use="optional"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="version" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== LeonardoHP29/tecweb/practicas/p14/spotify.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Ejercicio 1
<Spotify xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="spotify.xsd" version="1.0">
-->
<Spotify xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="spotify_v2.xsd" version="1.0">
    <Cuenta id="1" plan="premium" fechaIni="2022-02-01" fechaFin="2024-12-12">
        <Nombre>Leonardo Hernandez</Nombre>
        <Correo>leohdz2905@gmail.com</Correo>
        <Telefono Tipo="movil">2761100735</Telefono>
    </Cuenta>
    <Cuenta id="2" plan="basico">
        <Nombre>Ignacio Flores</Nombre>
        <Correo>IgnacioFlor@gmail.com</Correo>
    </Cuenta>
    <Cuenta id="3" plan="premium" fechaIni="2024-07-12">
        <Nombre>Michel Leon</Nombre>
        <Correo>MichelLeon@gmail.com</Correo>
        <Telefono Tipo="casa">77770202</Telefono>
    </Cuenta>
    <Cuenta id="4" plan="basico" fechaFin="2024-12-12">
        <Nombre>Damian Cocone</Nombre>
        <Correo>DamianCoc@gmail.com</Correo>
    </Cuenta>
</Spotify>
